# Generated by Django 4.2.23 on 2025-06-30 13:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='الماركة')),
            ],
            options={
                'verbose_name': 'ماركة',
                'verbose_name_plural': 'الماركات',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'فئة',
                'verbose_name_plural': 'الفئات',
            },
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_currency', models.CharField(default='SAR', max_length=3, verbose_name='عملة التسعير النهائية')),
                ('additional_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='رسوم إضافية ثابتة (بالعملة النهائية)')),
            ],
            options={
                'verbose_name': 'تفضيل',
                'verbose_name_plural': 'التفضيلات',
            },
        ),
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_keyword', models.CharField(max_length=255, unique=True, verbose_name='الكلمة المفتاحية للمنتج')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='تكلفة الشحن')),
                ('currency', models.CharField(default='AED', max_length=3, verbose_name='عملة الشحن')),
            ],
            options={
                'verbose_name': 'سعر الشحن',
                'verbose_name_plural': 'أسعار الشحن',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المشترك')),
                ('whatsapp_number', models.CharField(max_length=20, unique=True, verbose_name='رقم الواتساب')),
                ('subscriber_type', models.CharField(choices=[('INTERNAL', 'موظف/شريك (معفى من الرسوم)'), ('EXTERNAL', 'عميل خارجي (تطبق الرسوم)')], default='EXTERNAL', max_length=10, verbose_name='نوع المشترك')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط؟')),
            ],
            options={
                'verbose_name': 'مشترك',
                'verbose_name_plural': 'المشتركون',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='اسم المورد')),
                ('contact_info', models.TextField(blank=True, verbose_name='بيانات التواصل')),
                ('code', models.CharField(blank=True, max_length=10, unique=True, verbose_name='كود المورد')),
            ],
            options={
                'verbose_name': 'مورد',
                'verbose_name_plural': 'الموردون',
            },
        ),
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('AMOUNT', 'مبلغ ثابت'), ('PERCENT', 'نسبة مئوية')], default='AMOUNT', max_length=10, verbose_name='نوع الإضافة')),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='قيمة الإضافة')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.brand', verbose_name='الماركة المستهدفة')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.category', verbose_name='الفئة المستهدفة')),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='management.preference', verbose_name='ملف التفضيلات')),
            ],
            options={
                'verbose_name': 'قاعدة تسعير',
                'verbose_name_plural': 'قواعد التسعير',
            },
        ),
        migrations.AddField(
            model_name='preference',
            name='allowed_suppliers',
            field=models.ManyToManyField(blank=True, to='management.supplier', verbose_name='الموردون المسموح بهم'),
        ),
        migrations.AddField(
            model_name='preference',
            name='interested_brands',
            field=models.ManyToManyField(blank=True, to='management.brand', verbose_name='الماركات المهتم بها'),
        ),
        migrations.AddField(
            model_name='preference',
            name='interested_categories',
            field=models.ManyToManyField(blank=True, to='management.category', verbose_name='الفئات المهتم بها'),
        ),
        migrations.AddField(
            model_name='preference',
            name='subscriber',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='management.subscriber', verbose_name='المشترك'),
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المنتج/الموديل')),
                ('storage', models.CharField(blank=True, max_length=50, verbose_name='السعة')),
                ('condition', models.CharField(blank=True, max_length=100, verbose_name='الحالة')),
                ('spec_region', models.CharField(blank=True, max_length=100, verbose_name='المواصفة/المنطقة')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='اللون')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='الكمية')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='السعر الأصلي')),
                ('currency', models.CharField(blank=True, max_length=10, null=True, verbose_name='عملة السعر الأصلي')),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='تكلفة الشحن')),
                ('shipping_currency', models.CharField(blank=True, max_length=10, null=True, verbose_name='عملة الشحن')),
                ('code', models.CharField(blank=True, max_length=10, unique=True, verbose_name='كود العرض')),
                ('original_text', models.TextField(blank=True, help_text='النص الأصلي من رسالة المورد', verbose_name='النص الأصلي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.brand', verbose_name='الماركة')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.category', verbose_name='الفئة')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'عرض',
                'verbose_name_plural': 'العروض',
            },
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency', models.CharField(max_length=3, verbose_name='من عملة (e.g., USD)')),
                ('to_currency', models.CharField(max_length=3, verbose_name='إلى عملة (e.g., SAR)')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=15, verbose_name='معامل التحويل (للضرب)')),
            ],
            options={
                'verbose_name': 'سعر تحويل العملة',
                'verbose_name_plural': 'أسعار تحويل العملات',
                'unique_together': {('from_currency', 'to_currency')},
            },
        ),
        migrations.CreateModel(
            name='SubscriberDeviceFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_keyword', models.CharField(max_length=255, verbose_name='الكلمة المفتاحية للجهاز')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الرسم الإجباري')),
                ('currency', models.CharField(default='AED', max_length=3, verbose_name='عملة الرسم')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_fees', to='management.subscriber', verbose_name='المشترك')),
            ],
            options={
                'verbose_name': 'رسم جهاز للمشترك',
                'verbose_name_plural': 'رسوم الأجهزة للمشتركين',
                'unique_together': {('subscriber', 'device_keyword')},
            },
        ),
    ]
