# Generated by Django 4.2.23 on 2025-06-30 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_offer_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='كود العرض'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اللون'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='condition',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='original_text',
            field=models.TextField(blank=True, help_text='النص الأصلي من رسالة المورد', null=True, verbose_name='النص الأصلي'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='spec_region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المواصفة/المنطقة'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='storage',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='السعة'),
        ),
    ]
