# Generated by Django 4.2.23 on 2025-06-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_offer_code_alter_offer_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricerule',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='pricerule',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pricerule',
            name='preference',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='target_currency',
            field=models.CharField(default='SAR', max_length=3, verbose_name='عملة التسعير النهائية'),
        ),
        migrations.DeleteModel(
            name='Preference',
        ),
        migrations.DeleteModel(
            name='PriceRule',
        ),
    ]
