# Generated by Django 4.2.23 on 2025-07-02 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_remove_pricerule_brand_remove_pricerule_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_suppliers', models.ManyToManyField(blank=True, to='management.supplier', verbose_name='الموردون المسموح بهم (فارغ للكل)')),
                ('interested_brands', models.ManyToManyField(blank=True, to='management.brand', verbose_name='الماركات المهتم بها (فارغ للكل)')),
                ('interested_categories', models.ManyToManyField(blank=True, to='management.category', verbose_name='الفئات المهتم بها (فارغ للكل)')),
                ('subscriber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='management.subscriber', verbose_name='المشترك')),
            ],
            options={
                'verbose_name': 'ملف تفضيلات',
                'verbose_name_plural': 'ملفات التفضيلات',
            },
        ),
    ]
