# Generated by Django 4.2.23 on 2025-07-03 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_preference'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_type', models.CharField(max_length=50, verbose_name='نوع المتغير')),
                ('variant_value', models.CharField(max_length=100, verbose_name='قيمة المتغير')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='الكمية')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('price_currency', models.CharField(default='USD', max_length=3, verbose_name='عملة السعر')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='تكلفة الشحن')),
                ('shipping_currency', models.CharField(default='AED', max_length=3, verbose_name='عملة الشحن')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='management.offer', verbose_name='العرض الأساسي')),
            ],
            options={
                'verbose_name': 'نوع فرعي للعرض',
                'verbose_name_plural': 'أنواع فرعية للعرض',
            },
        ),
    ]
