# Generated by Django 4.2.23 on 2025-07-03 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_offervariant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OfferVariant',
        ),
    ]
