# Generated by Django 4.2.23 on 2025-07-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_delete_offervariant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingrate',
            options={'ordering': ['product_keyword_en'], 'verbose_name': 'سعر الشحن', 'verbose_name_plural': 'أسعار الشحن'},
        ),
        migrations.RemoveField(
            model_name='shippingrate',
            name='product_keyword',
        ),
        migrations.AddField(
            model_name='shippingrate',
            name='product_keyword_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الكلمة المفتاحية (العربية)'),
        ),
        migrations.AddField(
            model_name='shippingrate',
            name='product_keyword_en',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='الكلمة المفتاحية (الإنجليزية)'),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='تكلفة الشحن'),
        ),
    ]
